### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by xarem** [whatwedo/docker-base-images#5]
## new features / bc
- [x] creating `/bin/everyboot.d` instead of a single everyboot file
- [x] creating `/bin/firstboot.d` instead of a single firstboot file
- [ ] create different images for different ruby versions (currently 2.1, 2.2 and 2.3)
- [ ] use `--no-install-recommends` for [smaller images](https://blog.replicated.com/2016/02/05/refactoring-a-dockerfile-for-image-size/) and prevent [php7.1-cli installation](https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#why-is-php71-cli-always-installed) in older versions
- [ ] new `nginx-pagespeed` image

## refactoring
- [x] use same functions for the same task (e.g. always use `curl` for downloads, not `wget`)
- [x] check hashsum of every downloaded file
- [x] only add those files needed by the image in the `dist` folders
- [x] do apt cleanup after every apt run (see [comment of @chesty](https://github.com/whatwedo/docker-base-images/issues/5#issuecomment-261768852))
- [x] use [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) to check if all processes of supervisord are running
- [x] change docroot of nginx/apache to `/var/www/`
- [ ] remove wordpress-nginx-w3tc and create instead wordpress-nginx based on `nginx-pagespeed`
- [x] check if cron can be removed from base image

## proposals
- [ ] update to bionic beaver or use a smaller image
- [x] move image building to our own gitlab instance for a faster and better organised build process ([Link](https://dev.whatwedo.ch/whatwedo/docker-base-images))
- [x] define a build order so that `whatwedo/base` is always the first image to build ([Example](https://dev.whatwedo.ch/whatwedo/docker-base-images/pipelines/3652))
- [x] shrink [number of layers](https://imagelayers.io/?images=whatwedo%2Fbase:master) and the size of `whatwedo/base`

**Comment by chesty** [comment]
refactoring:
apt-get update and apt-get clean should be in every apt-get install RUN layer, and removed from head and cleanup.

RUN apt-get -y update && apt-get -y install blah1 blah2 blah3 && apt-get -y purge unwanted-packages-only-needed-for-building-not-running && apt-get --purge -y autoremove && apt-get -y clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

running apt-get clean in the last layer doesn't remove any files from the first layer where apt-get update was ran. there's also potential issues with a stale package cache described here https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

**Comment by xarem** [comment]
@chesty thanks for your input! i added this to our refactoring-checklist

**Comment by n3r0-ch** [comment]
Closing in favour of #25 and #26
